apiVersion: v1
kind: ServiceAccount
metadata:
  name: chakrator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chakrator
rules:
- apiGroups: ["example.com"]
  resources: ["myresources"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chakrator
subjects:
- kind: ServiceAccount
  name: chakrator
  namespace: default
roleRef:
  kind: ClusterRole
  name: chakrator
  apiGroup: rbac.authorization.k8s.io
